/* tslint:disable */
/* eslint-disable */
/**
 * sample_api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface GetUserId200Response
 */
export interface GetUserId200Response {
    /**
     * 
     * @type {GetUserId200ResponseUser}
     * @memberof GetUserId200Response
     */
    'user'?: GetUserId200ResponseUser;
}
/**
 * 
 * @export
 * @interface GetUserId200ResponseUser
 */
export interface GetUserId200ResponseUser {
    /**
     * 
     * @type {string}
     * @memberof GetUserId200ResponseUser
     */
    'name'?: string;
}
/**
 * 
 * @export
 * @interface PostUsersUserIdRequest
 */
export interface PostUsersUserIdRequest {
    /**
     * 
     * @type {PostUsersUserIdRequestUser}
     * @memberof PostUsersUserIdRequest
     */
    'user'?: PostUsersUserIdRequestUser;
}
/**
 * 
 * @export
 * @interface PostUsersUserIdRequestUser
 */
export interface PostUsersUserIdRequestUser {
    /**
     * 
     * @type {string}
     * @memberof PostUsersUserIdRequestUser
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostUsersUserIdRequestUser
     */
    'email'?: string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary ユーザー取得
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserId: async (userId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserId', 'userId', userId)
            const localVarPath = `/users/{user_id}`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary ユーザー更新
         * @param {string} userId 
         * @param {PostUsersUserIdRequest} [postUsersUserIdRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUsersUserId: async (userId: string, postUsersUserIdRequest?: PostUsersUserIdRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('postUsersUserId', 'userId', userId)
            const localVarPath = `/users/{user_id}`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postUsersUserIdRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary ユーザー取得
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserId(userId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserId200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserId(userId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary ユーザー更新
         * @param {string} userId 
         * @param {PostUsersUserIdRequest} [postUsersUserIdRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postUsersUserId(userId: string, postUsersUserIdRequest?: PostUsersUserIdRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserId200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postUsersUserId(userId, postUsersUserIdRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary ユーザー取得
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserId(userId: string, options?: any): AxiosPromise<GetUserId200Response> {
            return localVarFp.getUserId(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary ユーザー更新
         * @param {string} userId 
         * @param {PostUsersUserIdRequest} [postUsersUserIdRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUsersUserId(userId: string, postUsersUserIdRequest?: PostUsersUserIdRequest, options?: any): AxiosPromise<GetUserId200Response> {
            return localVarFp.postUsersUserId(userId, postUsersUserIdRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary ユーザー取得
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getUserId(userId: string, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getUserId(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary ユーザー更新
     * @param {string} userId 
     * @param {PostUsersUserIdRequest} [postUsersUserIdRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public postUsersUserId(userId: string, postUsersUserIdRequest?: PostUsersUserIdRequest, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).postUsersUserId(userId, postUsersUserIdRequest, options).then((request) => request(this.axios, this.basePath));
    }
}


