
version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./node:/usr/src/app:cached
    command: sh -c "cd customu && yarn start"
    ports:
      - "3000:3000"