openapi: 3.0.2
info:
  title: customu
  version: '1.0.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/healthybody/{day_id}':
    parameters:
      - schema:
          type: string
        name: day_id
        in: path
        required: true
    get:
      summary: daily detail
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      name:
                        type: string
      operationId: get-daily_id
      description: ''
#     post:
#       summary: ユーザー更新
#       operationId: post-users-user_id
#       responses:
#         '200':
#           description: OK
#           content:
#             application/json:
#               schema:
#                 type: object
#                 properties:
#                   user:
#                     type: object
#                     properties:
#                       name:
#                         type: string
#       requestBody:
#         content:
#           application/json:
#             schema:
#               type: object
#               properties:
#                 user:
#                   type: object
#                   properties:
#                     name:
#                       type: string
#                     email:
#                       type: string
#           application/xml:
#             schema:
#               type: object
#               properties:
#                 user:
#                   type: object
#                   properties:
#                     name:
#                       type: string
#         description: ''
components:
  schemas:
    
